-- Migration: Kochanleitung fuer kuratierte Rezepte (jsonb mit Aktions-Typ pro Schritt)
-- In Supabase SQL Editor ausfuehren (Projekt: wruiyvttftiyskyjjuio). Noch NICHT
-- ausgefuehrt - Gregor fuehrt sie manuell aus.

-- 1) Neue Spalte anlegen.
--    jsonb statt text[], weil jeder Schritt jetzt ZWEI Felder braucht: den
--    Anzeige-Text und einen 'aktion'-Typ (siehe unten) fuer ein spaeteres
--    Feature (animiertes Icon pro Kochschritt, z. B. Pfanne mit Dampf beim
--    Braten). Format: jsonb-Array aus Objekten { "text": string, "aktion": string }.
alter table rezepte add column if not exists anleitung jsonb;

-- 2) Erlaubte aktion-Werte (feste, ueberschaubare Liste - siehe CLAUDE.md):
--    schneiden, kochen, braten, roesten, ruehren, mischen, warten, servieren

-- 3) Kochanleitung fuer alle 30 bestehenden Rezepte.
update rezepte set anleitung = '[{"text": "Magerquark in eine Schüssel geben und mit einem Löffel glattrühren, bis er cremig ist.", "aktion": "ruehren"}, {"text": "Haferflocken unterheben und kurz ziehen lassen, damit sie leicht aufquellen.", "aktion": "warten"}, {"text": "Mandeln grob hacken und untermischen.", "aktion": "schneiden"}, {"text": "Heidelbeeren waschen, obenauf verteilen und sofort servieren.", "aktion": "servieren"}]'::jsonb where id = 1;
update rezepte set anleitung = '[{"text": "Griechisches Joghurt in eine Schüssel füllen und glattrühren.", "aktion": "ruehren"}, {"text": "Müsli darüberstreuen und kurz einziehen lassen.", "aktion": "warten"}, {"text": "Walnüsse grob hacken.", "aktion": "schneiden"}, {"text": "Banane in Scheiben schneiden, zusammen mit den Walnüssen obenauf verteilen und servieren.", "aktion": "servieren"}]'::jsonb where id = 2;
update rezepte set anleitung = '[{"text": "Skyr in eine Schüssel geben und glattrühren.", "aktion": "ruehren"}, {"text": "Haferflocken unterrühren, bis alles gut vermischt ist.", "aktion": "ruehren"}, {"text": "Kokosflocken darüberstreuen.", "aktion": "mischen"}, {"text": "Erdbeeren waschen, halbieren und auf der Bowl verteilen.", "aktion": "schneiden"}, {"text": "Sofort servieren, solange die Bowl schön frisch ist.", "aktion": "servieren"}]'::jsonb where id = 3;
update rezepte set anleitung = '[{"text": "Proteinjoghurt in eine Schüssel geben und glattrühren.", "aktion": "ruehren"}, {"text": "Haferflocken und Kokosflocken einrühren.", "aktion": "ruehren"}, {"text": "Kirschen entsteinen und daraufgeben.", "aktion": "schneiden"}, {"text": "Kurz durchziehen lassen, damit sich die Aromen verbinden, dann servieren.", "aktion": "warten"}]'::jsonb where id = 4;
update rezepte set anleitung = '[{"text": "Eier in kochendem Wasser ca. 6–7 Minuten wachsweich kochen.", "aktion": "kochen"}, {"text": "Währenddessen das Vollkornbrot goldbraun toasten.", "aktion": "roesten"}, {"text": "Avocado mit einer Gabel zerdrücken, salzen und pfeffern, dann auf dem Toast verteilen.", "aktion": "ruehren"}, {"text": "Paradeiser in Scheiben schneiden und daraufgeben.", "aktion": "schneiden"}, {"text": "Ei abschrecken, schälen, halbieren und obenauf setzen.", "aktion": "servieren"}]'::jsonb where id = 5;
update rezepte set anleitung = '[{"text": "Roggenbrot nach Belieben toasten oder frisch verwenden.", "aktion": "roesten"}, {"text": "Frischkäse gleichmäßig darauf verstreichen.", "aktion": "ruehren"}, {"text": "Lachs in Scheiben darauflegen.", "aktion": "schneiden"}, {"text": "Gurke in dünne Scheiben schneiden, darauf verteilen und servieren.", "aktion": "servieren"}]'::jsonb where id = 6;
update rezepte set anleitung = '[{"text": "Vollkornbrot goldbraun toasten.", "aktion": "roesten"}, {"text": "Hüttenkäse gleichmäßig darauf verteilen.", "aktion": "mischen"}, {"text": "Mit Olivenöl beträufeln und leicht pfeffern.", "aktion": "mischen"}, {"text": "Paprika in dünne Streifen schneiden, daraufgeben und servieren.", "aktion": "servieren"}]'::jsonb where id = 7;
update rezepte set anleitung = '[{"text": "Reis nach Packungsanweisung in Salzwasser kochen.", "aktion": "kochen"}, {"text": "Hähnchenbrust salzen und pfeffern, dann in einer Pfanne mit etwas Olivenöl bei mittlerer Hitze von beiden Seiten je 6–8 Minuten goldbraun braten, bis sie durch ist.", "aktion": "braten"}, {"text": "Brokkoli in Röschen teilen und in Salzwasser oder im Dampf 5–6 Minuten bissfest garen.", "aktion": "kochen"}, {"text": "Hähnchen in Scheiben schneiden und mit Reis und Brokkoli anrichten.", "aktion": "servieren"}]'::jsonb where id = 8;
update rezepte set anleitung = '[{"text": "Quinoa nach Packungsanweisung kochen und ausquellen lassen.", "aktion": "kochen"}, {"text": "Tofu in Würfel schneiden.", "aktion": "schneiden"}, {"text": "Tofu in Sesamöl bei mittlerer bis hoher Hitze rundherum knusprig anbraten.", "aktion": "braten"}, {"text": "Chinakohl in feine Streifen schneiden und die letzten Minuten mitdünsten.", "aktion": "braten"}, {"text": "Alles in einer Bowl anrichten und servieren.", "aktion": "servieren"}]'::jsonb where id = 9;
update rezepte set anleitung = '[{"text": "Süßkartoffel schälen, würfeln und mit Olivenöl vermengt im Ofen bei 200 °C ca. 20–25 Minuten weich rösten.", "aktion": "roesten"}, {"text": "Lachs salzen und pfeffern, dann in einer Pfanne von beiden Seiten braten, bis er gar ist.", "aktion": "braten"}, {"text": "Spinat kurz in derselben Pfanne zusammenfallen lassen.", "aktion": "braten"}, {"text": "Alles gemeinsam anrichten und servieren.", "aktion": "servieren"}]'::jsonb where id = 10;
update rezepte set anleitung = '[{"text": "Vollkornnudeln nach Packungsanweisung in Salzwasser kochen.", "aktion": "kochen"}, {"text": "Faschiertes in einer Pfanne mit Olivenöl krümelig anbraten, bis es durch ist.", "aktion": "braten"}, {"text": "Zucchini würfeln und mitbraten, bis sie weich ist.", "aktion": "braten"}, {"text": "Nudeln abgießen, unter die Sauce heben und servieren.", "aktion": "mischen"}]'::jsonb where id = 11;
update rezepte set anleitung = '[{"text": "Couscous mit kochendem Wasser übergießen, abdecken und 5 Minuten quellen lassen.", "aktion": "warten"}, {"text": "Couscous mit einer Gabel auflockern.", "aktion": "ruehren"}, {"text": "Kichererbsen abtropfen lassen und kurz erwärmen.", "aktion": "kochen"}, {"text": "Karotten raspeln oder in feine Streifen schneiden.", "aktion": "schneiden"}, {"text": "Alles mit Tahini beträufeln, vermengen und servieren.", "aktion": "mischen"}]'::jsonb where id = 12;
update rezepte set anleitung = '[{"text": "Erdäpfel schälen, in Stücke schneiden und in Salzwasser weich kochen.", "aktion": "kochen"}, {"text": "Putenbrust salzen und pfeffern, dann in Butter bei mittlerer Hitze goldbraun braten, bis sie durch ist.", "aktion": "braten"}, {"text": "Fisolen putzen und in Salzwasser 8–10 Minuten garen.", "aktion": "kochen"}, {"text": "Alles gemeinsam anrichten und servieren.", "aktion": "servieren"}]'::jsonb where id = 13;
update rezepte set anleitung = '[{"text": "Reis nach Packungsanweisung in Salzwasser kochen.", "aktion": "kochen"}, {"text": "Linsen abtropfen lassen und in einer Pfanne kurz erwärmen.", "aktion": "braten"}, {"text": "Paradeiser würfeln.", "aktion": "schneiden"}, {"text": "Alles mit etwas Olivenöl vermengen und servieren.", "aktion": "mischen"}]'::jsonb where id = 14;
update rezepte set anleitung = '[{"text": "Naturreis nach Packungsanweisung kochen.", "aktion": "kochen"}, {"text": "Garnelen in einer heißen Pfanne kurz scharf anbraten, bis sie rosa und durch sind.", "aktion": "braten"}, {"text": "Erdnussbutter mit etwas warmem Wasser glattrühren, bis eine cremige Sauce entsteht.", "aktion": "ruehren"}, {"text": "Karotten in feine Streifen schneiden.", "aktion": "schneiden"}, {"text": "Alles anrichten und mit der Erdnusssauce beträufeln.", "aktion": "servieren"}]'::jsonb where id = 15;
update rezepte set anleitung = '[{"text": "Buchweizen nach Packungsanweisung kochen.", "aktion": "kochen"}, {"text": "Tempeh in dünne Scheiben schneiden.", "aktion": "schneiden"}, {"text": "Tempeh in Sesamöl von beiden Seiten knusprig anbraten.", "aktion": "braten"}, {"text": "Aubergine würfeln und mitbraten, bis sie weich ist.", "aktion": "braten"}, {"text": "Alles in einer Bowl anrichten und servieren.", "aktion": "servieren"}]'::jsonb where id = 16;
update rezepte set anleitung = '[{"text": "Süßkartoffel schälen, würfeln und mit Olivenöl im Ofen bei 200 °C ca. 20–25 Minuten rösten.", "aktion": "roesten"}, {"text": "Kohlsprossen halbieren und für die letzten 15 Minuten mit in den Ofen geben.", "aktion": "roesten"}, {"text": "Hähnchenbrust salzen und pfeffern, dann in der Pfanne braten, bis sie durch ist.", "aktion": "braten"}, {"text": "Alles gemeinsam anrichten und servieren.", "aktion": "servieren"}]'::jsonb where id = 17;
update rezepte set anleitung = '[{"text": "Quinoa nach Packungsanweisung kochen und etwas abkühlen lassen.", "aktion": "kochen"}, {"text": "Kichererbsen abtropfen lassen.", "aktion": "mischen"}, {"text": "Paprika würfeln.", "aktion": "schneiden"}, {"text": "Quinoa, Kichererbsen und Paprika vermengen.", "aktion": "mischen"}, {"text": "Mit zerbröckeltem Feta bestreuen und servieren.", "aktion": "servieren"}]'::jsonb where id = 18;
update rezepte set anleitung = '[{"text": "Erdäpfel schälen, in Stücke schneiden und in Salzwasser weich kochen.", "aktion": "kochen"}, {"text": "Karotten in Scheiben schneiden und die letzten Minuten mitkochen.", "aktion": "kochen"}, {"text": "Steak gut salzen und in einer sehr heißen Pfanne von jeder Seite 2–3 Minuten scharf anbraten.", "aktion": "braten"}, {"text": "Steak vor dem Anschneiden kurz ruhen lassen.", "aktion": "warten"}, {"text": "Erdäpfel mit Butter stampfen, alles gemeinsam anrichten und servieren.", "aktion": "servieren"}]'::jsonb where id = 19;
update rezepte set anleitung = '[{"text": "Reis nach Packungsanweisung kochen.", "aktion": "kochen"}, {"text": "Tofu würfeln und in Sesamöl rundherum knusprig anbraten.", "aktion": "braten"}, {"text": "Brokkoli in Röschen teilen und mitdünsten, bis er bissfest ist.", "aktion": "braten"}, {"text": "Alles gemeinsam anrichten und servieren.", "aktion": "servieren"}]'::jsonb where id = 20;
update rezepte set anleitung = '[{"text": "Vollkornreis nach Packungsanweisung kochen.", "aktion": "kochen"}, {"text": "Spargel schälen (bei grünem Spargel reicht das untere Drittel) und in Salzwasser oder Olivenöl gar dünsten.", "aktion": "kochen"}, {"text": "Lachs salzen und pfeffern, dann in der Pfanne von beiden Seiten braten, bis er gar ist.", "aktion": "braten"}, {"text": "Alles gemeinsam anrichten und servieren.", "aktion": "servieren"}]'::jsonb where id = 21;
update rezepte set anleitung = '[{"text": "Süßkartoffel schälen, würfeln und in Olivenöl weich braten oder im Ofen rösten.", "aktion": "braten"}, {"text": "Rote Linsen nach Packungsanweisung in Wasser weich kochen.", "aktion": "kochen"}, {"text": "Spinat in die Pfanne geben und kurz zusammenfallen lassen.", "aktion": "braten"}, {"text": "Alles vermengen, nach Geschmack würzen und servieren.", "aktion": "mischen"}]'::jsonb where id = 22;
update rezepte set anleitung = '[{"text": "Vollkornnudeln nach Packungsanweisung in Salzwasser kochen.", "aktion": "kochen"}, {"text": "Putenbrust salzen und pfeffern, dann in Olivenöl anbraten, bis sie durch ist.", "aktion": "braten"}, {"text": "Champignons vierteln und mitbraten, bis sie Farbe annehmen.", "aktion": "braten"}, {"text": "Nudeln abgießen, untermengen und servieren.", "aktion": "mischen"}]'::jsonb where id = 23;
update rezepte set anleitung = '[{"text": "Erdäpfel schälen, würfeln und in Butter bei mittlerer Hitze goldbraun braten.", "aktion": "braten"}, {"text": "Fisolen putzen und mitbraten, bis sie bissfest sind.", "aktion": "braten"}, {"text": "Eier in einer Schüssel verquirlen und salzen.", "aktion": "ruehren"}, {"text": "Eier in die Pfanne geben und unter gelegentlichem Wenden stocken lassen.", "aktion": "braten"}]'::jsonb where id = 24;
update rezepte set anleitung = '[{"text": "Skyr in eine Schüssel geben und glattrühren.", "aktion": "ruehren"}, {"text": "Haferflocken unterrühren.", "aktion": "ruehren"}, {"text": "Mandeln grob hacken und einstreuen.", "aktion": "schneiden"}, {"text": "Mit Heidelbeeren garnieren und servieren.", "aktion": "servieren"}]'::jsonb where id = 25;
update rezepte set anleitung = '[{"text": "Hüttenkäse gleichmäßig auf den Reiswaffeln verteilen.", "aktion": "mischen"}, {"text": "Walnüsse grob hacken und darüberstreuen.", "aktion": "schneiden"}, {"text": "Apfel in dünne Scheiben schneiden, dazu anrichten und servieren.", "aktion": "servieren"}]'::jsonb where id = 26;
update rezepte set anleitung = '[{"text": "Kichererbsen abtropfen lassen und mit etwas Olivenöl sowie Gewürzen nach Wahl vermengen.", "aktion": "mischen"}, {"text": "Vollkornbrot toasten oder frisch verwenden.", "aktion": "roesten"}, {"text": "Gurke in Scheiben schneiden.", "aktion": "schneiden"}, {"text": "Kichererbsen auf dem Brot verteilen, mit Gurke servieren.", "aktion": "servieren"}]'::jsonb where id = 27;
update rezepte set anleitung = '[{"text": "Thunfisch abtropfen lassen.", "aktion": "mischen"}, {"text": "Avocado mit einer Gabel zerdrücken und auf den Reiswaffeln verteilen.", "aktion": "ruehren"}, {"text": "Thunfisch daraufgeben.", "aktion": "mischen"}, {"text": "Paradeiser würfeln, darüberstreuen und servieren.", "aktion": "servieren"}]'::jsonb where id = 28;
update rezepte set anleitung = '[{"text": "Edamame in Salzwasser 3–4 Minuten kochen und abtropfen lassen.", "aktion": "kochen"}, {"text": "Mit etwas Sesamöl vermengen.", "aktion": "mischen"}, {"text": "Karotten in feine Streifen schneiden.", "aktion": "schneiden"}, {"text": "Alles zusammen mit den Reiswaffeln anrichten und servieren.", "aktion": "servieren"}]'::jsonb where id = 29;
update rezepte set anleitung = '[{"text": "Vollkornbrot goldbraun toasten.", "aktion": "roesten"}, {"text": "Ricotta gleichmäßig darauf verstreichen.", "aktion": "ruehren"}, {"text": "Mit Olivenöl beträufeln.", "aktion": "mischen"}, {"text": "Rucola daraufgeben, leicht andrücken und servieren.", "aktion": "servieren"}]'::jsonb where id = 30;
